version: 2
updates:
  - package-ecosystem: npm
    directory: /projects/marketing
    target-branch: staging
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    groups:
      marketing-minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /infra
    target-branch: staging
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    groups:
      infrastructure-minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(actions)
    groups:
      actions-minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]
